version: '2'
services:
  testba-postgresql:
    image: postgres:11.6
    # volumes:
    #     - ~/volumes/jhipster/TestBA/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=TestBA
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
